language: python

python:
  - "2.7"

services: mongodb

# whitelist
branches:
  only:
    - master

install:
    pip install --quiet --use-mirrors pytest coverage

script: coverage run --source turbokit -m py.test

after_script:
    pip install --quiet --use-mirrors coveralls;
    coveralls;
